const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });
const mongoose = require('mongoose');
const Product = require('./models/Product');
const Category = require('./models/Category');

const products = [
  {
    name: 'QuantumCore XR Headset',
    slug: 'quantumcore-xr-headset',
    description: 'Experience next-generation mixed reality with the QuantumCore XR. Featuring 8K micro-OLED displays, 140° FOV, and sub-5ms latency for the most immersive experience ever created.',
    brand: 'NeoVerse',
    category: 'VR Headsets',
    price: 1299.99,
    discount: 15,
    stock: 25,
    images: ['/images/products/quantumcore-xr.jpg'],
    specifications: [
      { key: 'Display', value: '8K Micro-OLED' },
      { key: 'Field of View', value: '140°' },
      { key: 'Refresh Rate', value: '120Hz' },
      { key: 'Weight', value: '380g' },
    ],
    rating: 4.8,
    numReviews: 234,
    isVRSupported: true,
    isARSupported: true,
    aiScore: 9.5,
    featured: true,
    trending: true,
    newArrival: true,
    flashSale: false,
    tags: ['vr', 'xr', 'mixed-reality', 'headset', 'premium'],
  },
  {
    name: 'Hololens Edge Pro',
    slug: 'hololens-edge-pro',
    description: 'Enterprise-grade augmented reality glasses with real-time spatial mapping, gesture recognition, and all-day comfort for professionals.',
    brand: 'Microsoft',
    category: 'AR Glasses',
    price: 2499.99,
    discount: 0,
    stock: 10,
    images: ['/images/products/hololens-edge.jpg'],
    specifications: [
      { key: 'Display', value: 'Waveguide OLED' },
      { key: 'Battery Life', value: '8 hours' },
      { key: 'Field of View', value: '70°' },
      { key: 'Weight', value: '290g' },
    ],
    rating: 4.5,
    numReviews: 89,
    isARSupported: true,
    isVRSupported: false,
    aiScore: 8.7,
    featured: true,
    trending: false,
    newArrival: false,
    flashSale: false,
    tags: ['ar', 'enterprise', 'glasses', 'professional'],
  },
  {
    name: 'HapticGlove X1',
    slug: 'hapticglove-x1',
    description: 'Full-finger haptic feedback gloves with 200+ tactile actuators per hand. Feel virtual objects with stunning realism.',
    brand: 'NeoVerse',
    category: 'Controllers',
    price: 599.99,
    discount: 10,
    stock: 50,
    images: ['/images/products/hapticglove-x1.jpg'],
    specifications: [
      { key: 'Actuators', value: '204 per hand' },
      { key: 'Connectivity', value: 'Bluetooth 5.3' },
      { key: 'Battery Life', value: '6 hours' },
      { key: 'Latency', value: '3ms' },
    ],
    rating: 4.6,
    numReviews: 156,
    isVRSupported: true,
    isARSupported: false,
    aiScore: 8.9,
    featured: true,
    trending: true,
    newArrival: true,
    flashSale: false,
    tags: ['haptic', 'gloves', 'controllers', 'touch'],
  },
  {
    name: 'NeuralLink Interface S2',
    slug: 'neurallink-interface-s2',
    description: 'Brain-computer interface wristband that reads neural signals to control devices with your thoughts. Non-invasive and highly accurate.',
    brand: 'NeuroSync',
    category: 'Wearables',
    price: 799.99,
    discount: 5,
    stock: 15,
    images: ['/images/products/neurallink-s2.jpg'],
    specifications: [
      { key: 'Sensors', value: '128-channel EEG' },
      { key: 'Accuracy', value: '97.3%' },
      { key: 'Battery', value: '12 hours' },
      { key: 'Compatibility', value: 'iOS, Android, Windows' },
    ],
    rating: 4.3,
    numReviews: 67,
    isARSupported: false,
    isVRSupported: false,
    aiScore: 9.1,
    featured: true,
    trending: true,
    newArrival: true,
    flashSale: false,
    tags: ['bci', 'neural', 'wearable', 'interface'],
  },
  {
    name: 'CyberBlade Gaming Suit',
    slug: 'cyberblade-gaming-suit',
    description: 'Full-body haptic feedback suit with 500+ vibration nodes, temperature simulation, and motion tracking for unparalleled gaming immersion.',
    brand: 'HapticTech',
    category: 'Wearables',
    price: 1899.99,
    discount: 20,
    stock: 8,
    images: ['/images/products/cyberblade-suit.jpg'],
    specifications: [
      { key: 'Haptic Nodes', value: '512' },
      { key: 'Temperature Range', value: '-5°C to 45°C' },
      { key: 'Tracking', value: 'IMU + Optical' },
      { key: 'Weight', value: '2.1kg' },
    ],
    rating: 4.7,
    numReviews: 112,
    isVRSupported: true,
    isARSupported: false,
    aiScore: 8.5,
    featured: false,
    trending: true,
    newArrival: false,
    flashSale: false,
    tags: ['haptic', 'suit', 'gaming', 'body', 'wearable'],
  },
  {
    name: 'AuraView Smart Glasses',
    slug: 'auraview-smart-glasses',
    description: 'Stylish everyday smart glasses with heads-up display, AI assistant, and 5G connectivity. Looks like regular eyewear, works like a supercomputer.',
    brand: 'MetaLens',
    category: 'AR Glasses',
    price: 449.99,
    discount: 0,
    stock: 100,
    images: ['/images/products/auraview.jpg'],
    specifications: [
      { key: 'Display', value: 'Retina Projection' },
      { key: 'Processor', value: 'Snapdragon AR2 Gen2' },
      { key: 'Camera', value: '48MP' },
      { key: 'Weight', value: '45g' },
    ],
    rating: 4.4,
    numReviews: 423,
    isARSupported: true,
    isVRSupported: false,
    aiScore: 7.8,
    featured: false,
    trending: false,
    newArrival: true,
    flashSale: false,
    tags: ['ar', 'glasses', 'smart', 'everyday', 'ai'],
  },
  {
    name: 'OmniTread VR Treadmill',
    slug: 'omnitread-vr-treadmill',
    description: 'Omni-directional treadmill with zero-friction movement for natural walking, running, and jumping in VR. Compact design fits any room.',
    brand: 'VirtuWalk',
    category: 'Accessories',
    price: 2999.99,
    discount: 10,
    stock: 5,
    images: ['/images/products/omnitread.jpg'],
    specifications: [
      { key: 'Surface', value: '1.5m² Omni-Directional' },
      { key: 'Max Speed', value: '15 km/h' },
      { key: 'Weight Limit', value: '150kg' },
      { key: 'Setup Area', value: '2.5m x 2.5m' },
    ],
    rating: 4.9,
    numReviews: 45,
    isVRSupported: true,
    isARSupported: false,
    aiScore: 6.5,
    featured: true,
    trending: false,
    newArrival: false,
    flashSale: false,
    tags: ['treadmill', 'movement', 'accessory', 'premium'],
  },
  {
    name: 'Holodeck Mini Projector',
    slug: 'holodeck-mini-projector',
    description: 'Desktop holographic projector that creates interactive 3D holograms in your space. Perfect for design reviews, education, and entertainment.',
    brand: 'NeoVerse',
    category: 'Accessories',
    price: 899.99,
    discount: 0,
    stock: 30,
    images: ['/images/products/holodeck-mini.jpg'],
    specifications: [
      { key: 'Resolution', value: '2K Holographic' },
      { key: 'Interaction', value: 'Gesture + Voice' },
      { key: 'Connectivity', value: 'Wi-Fi 6E, USB-C' },
      { key: 'Dimensions', value: '20cm x 15cm x 8cm' },
    ],
    rating: 4.2,
    numReviews: 78,
    isARSupported: true,
    isVRSupported: false,
    aiScore: 7.2,
    featured: false,
    trending: false,
    newArrival: true,
    flashSale: false,
    tags: ['hologram', 'projector', 'desktop', 'ar'],
  },
  {
    name: 'VR Motion Chair Pro',
    slug: 'vr-motion-chair-pro',
    description: '6-axis motion simulation chair that tilts, rotates, and vibrates in sync with your VR experience. Supports all major VR platforms.',
    brand: 'MotionSync',
    category: 'Accessories',
    price: 1599.99,
    discount: 25,
    stock: 12,
    images: ['/images/products/motion-chair.jpg'],
    specifications: [
      { key: 'Axis', value: '6-DOF' },
      { key: 'Rotation', value: '360°' },
      { key: 'Weight Capacity', value: '180kg' },
      { key: 'Audio', value: 'Built-in 5.1 Surround' },
    ],
    rating: 4.6,
    numReviews: 189,
    isVRSupported: true,
    isARSupported: false,
    aiScore: 6.8,
    featured: false,
    trending: true,
    newArrival: false,
    flashSale: true,
    tags: ['chair', 'motion', 'vr', 'accessory', 'sale'],
  },
  {
    name: 'PixelRay VR Camera',
    slug: 'pixelray-vr-camera',
    description: 'Professional 360° VR camera with 12K resolution, spatial audio recording, and real-time 3D stitching for immersive content creation.',
    brand: 'PixelRay',
    category: 'Cameras',
    price: 3499.99,
    discount: 0,
    stock: 7,
    images: ['/images/products/pixelray-camera.jpg'],
    specifications: [
      { key: 'Resolution', value: '12K (12288 x 6144)' },
      { key: 'Audio', value: 'Spatial 3D' },
      { key: 'Frame Rate', value: '60fps' },
      { key: 'Storage', value: '2TB Internal' },
    ],
    rating: 4.7,
    numReviews: 34,
    isVRSupported: true,
    isARSupported: false,
    aiScore: 8.0,
    featured: false,
    trending: false,
    newArrival: false,
    flashSale: false,
    tags: ['camera', '360', 'vr', 'professional', 'content'],
  },
  {
    name: 'SonicWave Spatial Earbuds',
    slug: 'sonicwave-spatial-earbuds',
    description: 'Spatial audio earbuds with head-tracking, 3D sound positioning, and AI-powered noise cancellation for the ultimate VR audio experience.',
    brand: 'NeoVerse',
    category: 'Audio',
    price: 249.99,
    discount: 0,
    stock: 200,
    images: ['/images/products/sonicwave-earbuds.jpg'],
    specifications: [
      { key: 'Audio', value: 'Spatial 3D with Head Tracking' },
      { key: 'Driver', value: '16mm Dynamic' },
      { key: 'Battery', value: '10 hours' },
      { key: 'Latency', value: '28ms (Low Latency Mode)' },
    ],
    rating: 4.5,
    numReviews: 567,
    isVRSupported: true,
    isARSupported: true,
    aiScore: 7.5,
    featured: false,
    trending: false,
    newArrival: true,
    flashSale: false,
    tags: ['audio', 'earbuds', 'spatial', 'wireless'],
  },
  {
    name: 'ARKit Developer Studio',
    slug: 'arkit-developer-studio',
    description: 'Complete AR development kit with advanced hand-tracking cameras, depth sensors, and Unity integration for building next-gen AR experiences.',
    brand: 'DevForge',
    category: 'Development Kits',
    price: 1999.99,
    discount: 0,
    stock: 20,
    images: ['/images/products/arkit-studio.jpg'],
    specifications: [
      { key: 'Sensors', value: 'LiDAR + Depth + IMU' },
      { key: 'Tracking', value: 'Hand + Eye + Face' },
      { key: 'SDK', value: 'Unity, Unreal, WebXR' },
      { key: 'Connectivity', value: 'USB-C, Wi-Fi 6, Bluetooth 5.3' },
    ],
    rating: 4.8,
    numReviews: 92,
    isARSupported: true,
    isVRSupported: false,
    aiScore: 9.2,
    featured: true,
    trending: false,
    newArrival: false,
    flashSale: false,
    tags: ['developer', 'ar', 'kit', 'studio', 'professional'],
  },
  {
    name: 'CyberLink VR Tread 2.0',
    slug: 'cyberlink-vr-tread-2',
    description: 'Next-gen VR treadmill with AI-powered stride adaptation, silent operation, and compact foldable design. Walk infinitely in any virtual world.',
    brand: 'VirtuWalk',
    category: 'Accessories',
    price: 2199.99,
    discount: 15,
    stock: 3,
    images: ['/images/products/cyberlink-tread.jpg'],
    specifications: [
      { key: 'Technology', value: 'AI Stride Adaptation' },
      { key: 'Noise Level', value: '< 25dB' },
      { key: 'Foldable', value: 'Yes' },
      { key: 'Max User Weight', value: '160kg' },
    ],
    rating: 4.4,
    numReviews: 28,
    isVRSupported: true,
    isARSupported: false,
    aiScore: 7.0,
    featured: false,
    trending: false,
    newArrival: true,
    flashSale: false,
    tags: ['treadmill', 'vr', 'tread', 'accessory', 'new'],
  },
  {
    name: 'NovaLens Contact Lenses',
    slug: 'novalens-contact-lenses',
    description: 'Smart contact lenses with micro-LED display, real-time AR overlay, and health monitoring sensors. The invisible future of augmented reality.',
    brand: 'BioVision',
    category: 'AR Glasses',
    price: 4999.99,
    discount: 0,
    stock: 2,
    images: ['/images/products/novalens.jpg'],
    specifications: [
      { key: 'Display', value: 'Micro-LED Array' },
      { key: 'Resolution', value: '480p per lens' },
      { key: 'Sensors', value: 'Glucose, Heart Rate, Eye Tracking' },
      { key: 'Battery', value: 'Wireless Charging Case' },
    ],
    rating: 4.1,
    numReviews: 12,
    isARSupported: true,
    isVRSupported: false,
    aiScore: 9.8,
    featured: false,
    trending: true,
    newArrival: false,
    flashSale: false,
    tags: ['ar', 'contact', 'lenses', 'smart', 'medical', 'premium'],
  },
  {
    name: 'PhantomStrike VR Controller',
    slug: 'phantomstrike-vr-controller',
    description: 'Ergonomic VR controllers with adaptive triggers, haptic feedback, finger tracking, and modular design for all grip styles.',
    brand: 'NeoVerse',
    category: 'Controllers',
    price: 199.99,
    discount: 0,
    stock: 150,
    images: ['/images/products/phantomstrike.jpg'],
    specifications: [
      { key: 'Tracking', value: 'Optical + IMU Fusion' },
      { key: 'Haptics', value: 'Adaptive + HD' },
      { key: 'Battery', value: '20 hours' },
      { key: 'Weight', value: '168g per controller' },
    ],
    rating: 4.6,
    numReviews: 890,
    isVRSupported: true,
    isARSupported: false,
    aiScore: 7.3,
    featured: false,
    trending: false,
    newArrival: false,
    flashSale: true,
    tags: ['controller', 'vr', 'gaming', 'handheld', 'sale'],
  },
];

const categories = [
  { name: 'VR Headsets', slug: 'vr-headsets', image: '/images/categories/vr-headsets.jpg', description: 'Virtual reality headsets for immersive experiences' },
  { name: 'AR Glasses', slug: 'ar-glasses', image: '/images/categories/ar-glasses.jpg', description: 'Augmented reality glasses for everyday use' },
  { name: 'Controllers', slug: 'controllers', image: '/images/categories/controllers.jpg', description: 'VR and AR controllers for precise interaction' },
  { name: 'Wearables', slug: 'wearables', image: '/images/categories/wearables.jpg', description: 'Wearable tech for the future' },
  { name: 'Accessories', slug: 'accessories', image: '/images/categories/accessories.jpg', description: 'Essential accessories for your VR/AR setup' },
  { name: 'Cameras', slug: 'cameras', image: '/images/categories/cameras.jpg', description: '360° and VR cameras for content creation' },
  { name: 'Audio', slug: 'audio', image: '/images/categories/audio.jpg', description: 'Spatial audio for immersive sound' },
  { name: 'Development Kits', slug: 'development-kits', image: '/images/categories/development-kits.jpg', description: 'Developer kits for building AR/VR experiences' },
];

const runSeed = async () => {
  await Category.insertMany(categories);
  await Product.insertMany(products);
  console.log(`Seeded ${categories.length} categories`);
  console.log(`Seeded ${products.length} products`);
};

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    console.log('Note: Users are managed by Clerk. Sign up via the frontend to create your account.');
    console.log('To set an admin role, update the user document in MongoDB after signup.');

    await Product.deleteMany({});
    await Category.deleteMany({});
    console.log('Cleared existing data');

    await runSeed();

    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

if (require.main === module) {
  seed();
}

module.exports = { runSeed, products, categories };
